### ISSUE TITLE
No suitable MP3 encoders available  

### ISSUE THREAD

**Issue by metapea** [weespin/WillFromAfarDownloader#15]
It was working fine until now
Error log:
```
************** Exception Text **************
System.InvalidOperationException: No suitable MP3 encoders available
   at NAudio.Wave.MediaFoundationEncoder.EncodeToMp3(IWaveProvider inputProvider, String outputFile, Int32 desiredBitRate)
   at AcapellaDownloader.Form1.btnDownload_Click(Object sender, EventArgs e) in 
 Users\*****\Source\Repos\WillFromAfarDownloader\AcapellaDownloader\Form1.cs:line 40
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///X:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AcapellaDownloader
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///X:/Users/kovon/Downloads/Release%20(1)/AcapellaDownloader.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
NAudio
    Assembly Version: 1.10.0.0
    Win32 Version: 1.10.0.0
    CodeBase: file:///X:/Users/kovon/Downloads/Release%20(1)/NAudio.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///X:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by weespin** [comment]
https://github.com/weespin/WillFromAfarDownloader#requirements
I guess you're using Windows 7

**Comment by metapea** [comment]
damn, it was working fine in Windows 7 before.

**Comment by weespin** [comment]
> damn, it was working fine in Windows 7 before.

Yeah, i've changed the audio library to support native mp3 decoding and Windows 7 doesn't support it.
You can still use the older version
I'll update WillFromAfarDownloader to support Windows 7 again but with some limitations
EDIT:
Updated! https://github.com/weespin/WillFromAfarDownloader/commit/d561efcadf3f9e88222ad6fdc4672499b3dbd93b
